<a href="https://colab.research.google.com/github/LeeGyuWon0427/Python-code-with-BJ/blob/main/0911_%EB%B0%B0%EB%8B%AC_delivery.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/deliverytime.csv')
df

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Type_of_order,Type_of_vehicle,Time_taken(min)
0,4607,INDORES13DEL02,37,4.9,22.745049,75.892471,22.765049,75.912471,Snack,motorcycle,24
1,B379,BANGRES18DEL02,34,4.5,12.913041,77.683237,13.043041,77.813237,Snack,scooter,33
2,5D6D,BANGRES19DEL01,23,4.4,12.914264,77.678400,12.924264,77.688400,Drinks,motorcycle,26
3,7A6A,COIMBRES13DEL02,38,4.7,11.003669,76.976494,11.053669,77.026494,Buffet,motorcycle,21
4,70A2,CHENRES12DEL01,32,4.6,12.972793,80.249982,13.012793,80.289982,Snack,scooter,30
...,...,...,...,...,...,...,...,...,...,...,...
45588,7C09,JAPRES04DEL01,30,4.8,26.902328,75.794257,26.912328,75.804257,Meal,motorcycle,32
45589,D641,AGRRES16DEL01,21,4.6,0.000000,0.000000,0.070000,0.070000,Buffet,motorcycle,36
45590,4F8D,CHENRES08DEL03,30,4.9,13.022394,80.242439,13.052394,80.272439,Drinks,scooter,16
45591,5EEE,COIMBRES11DEL01,20,4.7,11.001753,76.986241,11.041753,77.026241,Snack,motorcycle,26
45592,5FB2,RANCHIRES09DEL02,23,4.9,23.351058,85.325731,23.431058,85.405731,Snack,scooter,36

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45593 entries, 0 to 45592
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           45593 non-null  object
 1   Delivery_person_ID           45593 non-null  object
 2   Delivery_person_Age          45593 non-null  int64
 3   Delivery_person_Ratings      45593 non-null  float64
 4   Restaurant_latitude          45593 non-null  float64
 5   Restaurant_longitude         45593 non-null  float64
 6   Delivery_location_latitude   45593 non-null  float64
 7   Delivery_location_longitude  45593 non-null  float64
 8   Type_of_order                45593 non-null  object
 9   Type_of_vehicle              45593 non-null  object
 10  Time_taken(min)              45593 non-null  int64
dtypes: float64(5), int64(2), object(4)
memory usage: 3.8+ MB

In [ ]:
df.isnull().sum()

ID                             0
Delivery_person_ID             0
Delivery_person_Age            0
Delivery_person_Ratings        0
Restaurant_latitude            0
Restaurant_longitude           0
Delivery_location_latitude     0
Delivery_location_longitude    0
Type_of_order                  0
Type_of_vehicle                0
Time_taken(min)                0
dtype: int64

In [ ]:
df.describe()

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Time_taken(min)
count,45593.000000,45593.000000,45593.000000,45593.000000,45593.000000,45593.000000,45593.000000
mean,29.544075,4.632367,17.017729,70.231332,17.465186,70.845702,26.294607
std,5.696793,0.327708,8.185109,22.883647,7.335122,21.118812,9.383806
min,15.000000,1.000000,-30.905562,-88.366217,0.010000,0.010000,10.000000
25%,25.000000,4.600000,12.933284,73.170000,12.988453,73.280000,19.000000
50%,29.000000,4.700000,18.546947,75.898497,18.633934,76.002574,26.000000
75%,34.000000,4.800000,22.728163,78.044095,22.785049,78.107044,32.000000
max,50.000000,6.000000,30.914057,88.433452,31.054057,88.563452,54.000000

In [ ]:
df.columns

Index(['ID', 'Delivery_person_ID', 'Delivery_person_Age',
       'Delivery_person_Ratings', 'Restaurant_latitude',
       'Restaurant_longitude', 'Delivery_location_latitude',
       'Delivery_location_longitude', 'Type_of_order', 'Type_of_vehicle',
       'Time_taken(min)'],
      dtype='object')

In [ ]:
df.columns = ['ID', 'Delivery_person_ID', 'Delivery_person_Age',
       'Delivery_person_Ratings', 'Restaurant_latitude',
       'Restaurant_longitude', 'Delivery_location_latitude',
       'Delivery_location_longitude', 'Type_of_order', 'Type_of_vehicle',
       'Time_taken(min)']
df

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Type_of_order,Type_of_vehicle,Time_taken(min)
0,4607,INDORES13DEL02,37,4.9,22.745049,75.892471,22.765049,75.912471,Snack,motorcycle,24
1,B379,BANGRES18DEL02,34,4.5,12.913041,77.683237,13.043041,77.813237,Snack,scooter,33
2,5D6D,BANGRES19DEL01,23,4.4,12.914264,77.678400,12.924264,77.688400,Drinks,motorcycle,26
3,7A6A,COIMBRES13DEL02,38,4.7,11.003669,76.976494,11.053669,77.026494,Buffet,motorcycle,21
4,70A2,CHENRES12DEL01,32,4.6,12.972793,80.249982,13.012793,80.289982,Snack,scooter,30
...,...,...,...,...,...,...,...,...,...,...,...
45588,7C09,JAPRES04DEL01,30,4.8,26.902328,75.794257,26.912328,75.804257,Meal,motorcycle,32
45589,D641,AGRRES16DEL01,21,4.6,0.000000,0.000000,0.070000,0.070000,Buffet,motorcycle,36
45590,4F8D,CHENRES08DEL03,30,4.9,13.022394,80.242439,13.052394,80.272439,Drinks,scooter,16
45591,5EEE,COIMBRES11DEL01,20,4.7,11.001753,76.986241,11.041753,77.026241,Snack,motorcycle,26
45592,5FB2,RANCHIRES09DEL02,23,4.9,23.351058,85.325731,23.431058,85.405731,Snack,scooter,36

In [ ]:
df['Time_taken(min)'].unique()

array([24, 33, 26, 21, 30, 40, 32, 34, 46, 23, 20, 41, 15, 36, 39, 18, 38,
       47, 12, 22, 25, 35, 10, 19, 11, 28, 52, 16, 27, 49, 17, 14, 37, 44,
       42, 31, 13, 29, 50, 43, 48, 54, 53, 45, 51])

In [ ]:
df["Type_of_order"].unique()

array(['Snack ', 'Drinks ', 'Buffet ', 'Meal '], dtype=object)

In [ ]:
df["Type_of_vehicle"].unique()

array(['motorcycle ', 'scooter ', 'electric_scooter ', 'bicycle '],
      dtype=object)

In [ ]:
x = df.drop(columns=['Delivery_person_ID', 'ID'])
y = df['Time_taken(min)']
x

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Type_of_order,Type_of_vehicle,Time_taken(min)
0,37,4.9,22.745049,75.892471,22.765049,75.912471,Snack,motorcycle,24
1,34,4.5,12.913041,77.683237,13.043041,77.813237,Snack,scooter,33
2,23,4.4,12.914264,77.678400,12.924264,77.688400,Drinks,motorcycle,26
3,38,4.7,11.003669,76.976494,11.053669,77.026494,Buffet,motorcycle,21
4,32,4.6,12.972793,80.249982,13.012793,80.289982,Snack,scooter,30
...,...,...,...,...,...,...,...,...,...
45588,30,4.8,26.902328,75.794257,26.912328,75.804257,Meal,motorcycle,32
45589,21,4.6,0.000000,0.000000,0.070000,0.070000,Buffet,motorcycle,36
45590,30,4.9,13.022394,80.242439,13.052394,80.272439,Drinks,scooter,16
45591,20,4.7,11.001753,76.986241,11.041753,77.026241,Snack,motorcycle,26
45592,23,4.9,23.351058,85.325731,23.431058,85.405731,Snack,scooter,36

In [ ]:
y

0        24
1        33
2        26
3        21
4        30
         ..
45588    32
45589    36
45590    16
45591    26
45592    36
Name: Time_taken(min), Length: 45593, dtype: int64

In [ ]:
df['la'] = df['Restaurant_latitude'] - df['Delivery_location_latitude']
df['la'] = df['la'].abs()
df['la']

0        0.02
1        0.13
2        0.01
3        0.05
4        0.04
         ...
45588    0.01
45589    0.07
45590    0.03
45591    0.04
45592    0.08
Name: la, Length: 45593, dtype: float64

In [ ]:
df['Type_of_vehicle'] = df['Type_of_vehicle'].str.rstrip()
df['Type_of_vehicle'] = df['Type_of_vehicle'].str.replace('electric_scooter','scooter')
df['Type_of_order'] = df['Type_of_order'].str.replace('Buffet','Meal')

In [ ]:
df['Type_of_vehicle'].unique()

array(['motorcycle', 'scooter', 'bicycle'], dtype=object)

In [ ]:
vehicle_mapping = {'motorcycle': 2, 'scooter': 0, 'bicycle': 1}
x['Type_of_vehicle'] = x['Type_of_vehicle'].map(vehicle_mapping)
x

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Type_of_order,Type_of_vehicle,Time_taken(min)
0,37,4.9,22.745049,75.892471,22.765049,75.912471,Snack,NaN,24
1,34,4.5,12.913041,77.683237,13.043041,77.813237,Snack,NaN,33
2,23,4.4,12.914264,77.678400,12.924264,77.688400,Drinks,NaN,26
3,38,4.7,11.003669,76.976494,11.053669,77.026494,Buffet,NaN,21
4,32,4.6,12.972793,80.249982,13.012793,80.289982,Snack,NaN,30
...,...,...,...,...,...,...,...,...,...
45588,30,4.8,26.902328,75.794257,26.912328,75.804257,Meal,NaN,32
45589,21,4.6,0.000000,0.000000,0.070000,0.070000,Buffet,NaN,36
45590,30,4.9,13.022394,80.242439,13.052394,80.272439,Drinks,NaN,16
45591,20,4.7,11.001753,76.986241,11.041753,77.026241,Snack,NaN,26
45592,23,4.9,23.351058,85.325731,23.431058,85.405731,Snack,NaN,36

In [ ]:
order_mapping = {'Meal': 0, 'Drinks': 1, 'Snack': 2, 'Meal': 3}
x['Type_of_order'] = x['Type_of_order'].map(order_mapping)
x

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Type_of_order,Type_of_vehicle,Time_taken(min)
0,37,4.9,22.745049,75.892471,22.765049,75.912471,NaN,NaN,24
1,34,4.5,12.913041,77.683237,13.043041,77.813237,NaN,NaN,33
2,23,4.4,12.914264,77.678400,12.924264,77.688400,NaN,NaN,26
3,38,4.7,11.003669,76.976494,11.053669,77.026494,NaN,NaN,21
4,32,4.6,12.972793,80.249982,13.012793,80.289982,NaN,NaN,30
...,...,...,...,...,...,...,...,...,...
45588,30,4.8,26.902328,75.794257,26.912328,75.804257,NaN,NaN,32
45589,21,4.6,0.000000,0.000000,0.070000,0.070000,NaN,NaN,36
45590,30,4.9,13.022394,80.242439,13.052394,80.272439,NaN,NaN,16
45591,20,4.7,11.001753,76.986241,11.041753,77.026241,NaN,NaN,26
45592,23,4.9,23.351058,85.325731,23.431058,85.405731,NaN,NaN,36

In [ ]:
x

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Type_of_order,Type_of_vehicle,Time_taken(min)
0,37,4.9,22.745049,75.892471,22.765049,75.912471,NaN,NaN,24
1,34,4.5,12.913041,77.683237,13.043041,77.813237,NaN,NaN,33
2,23,4.4,12.914264,77.678400,12.924264,77.688400,NaN,NaN,26
3,38,4.7,11.003669,76.976494,11.053669,77.026494,NaN,NaN,21
4,32,4.6,12.972793,80.249982,13.012793,80.289982,NaN,NaN,30
...,...,...,...,...,...,...,...,...,...
45588,30,4.8,26.902328,75.794257,26.912328,75.804257,NaN,NaN,32
45589,21,4.6,0.000000,0.000000,0.070000,0.070000,NaN,NaN,36
45590,30,4.9,13.022394,80.242439,13.052394,80.272439,NaN,NaN,16
45591,20,4.7,11.001753,76.986241,11.041753,77.026241,NaN,NaN,26
45592,23,4.9,23.351058,85.325731,23.431058,85.405731,NaN,NaN,36

In [ ]:
df['Type_of_order'].unique()

array(['Snack ', 'Drinks ', 'Meal '], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.tree import DecisionTreeRegressor
model = DecisionTreeRegressor(max_depth=5, random_state=42)
model.fit(train_X, train_y)

DecisionTreeRegressor(max_depth=5, random_state=42)

In [ ]:
model.score(train_X, train_y)

0.9990558053787852

In [ ]:
model.score(test_X, test_y)

0.9990569412660649